{
 "title": "Lab07-Logs",
 "tags": [
  "lab07",
  "loki",
  "observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs Table",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"devops-.*\"}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app) (rate({app=~\"devops-.*\"}[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=~\"devops-.*\"} | json | level=\"ERROR\""
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({app=~\"devops-.*\"} | json [5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}